// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package endpoint

import (
	service "books/pkg/service"
	endpoint "github.com/go-kit/kit/endpoint"
)

// Endpoints collects all of the endpoints that compose a profile service. It's
// meant to be used as a helper struct, to collect all of the endpoints into a
// single parameter.
type Endpoints struct {
	CreateEndpoint                 endpoint.Endpoint
	UpdateEndpoint                 endpoint.Endpoint
	DeleteEndpoint                 endpoint.Endpoint
	PublishEndpoint                endpoint.Endpoint
	GetBookEndpoint                endpoint.Endpoint
	SendEmailBookPublishedEndpoint endpoint.Endpoint
}

// New returns a Endpoints struct that wraps the provided service, and wires in all of the
// expected endpoint middlewares
func New(s service.BooksService, mdw map[string][]endpoint.Middleware) Endpoints {
	eps := Endpoints{
		CreateEndpoint:                 MakeCreateEndpoint(s),
		DeleteEndpoint:                 MakeDeleteEndpoint(s),
		GetBookEndpoint:                MakeGetBookEndpoint(s),
		PublishEndpoint:                MakePublishEndpoint(s),
		SendEmailBookPublishedEndpoint: MakeSendEmailBookPublishedEndpoint(s),
		UpdateEndpoint:                 MakeUpdateEndpoint(s),
	}
	for _, m := range mdw["Create"] {
		eps.CreateEndpoint = m(eps.CreateEndpoint)
	}
	for _, m := range mdw["Update"] {
		eps.UpdateEndpoint = m(eps.UpdateEndpoint)
	}
	for _, m := range mdw["Delete"] {
		eps.DeleteEndpoint = m(eps.DeleteEndpoint)
	}
	for _, m := range mdw["Publish"] {
		eps.PublishEndpoint = m(eps.PublishEndpoint)
	}
	for _, m := range mdw["GetBook"] {
		eps.GetBookEndpoint = m(eps.GetBookEndpoint)
	}
	for _, m := range mdw["SendEmailBookPublished"] {
		eps.SendEmailBookPublishedEndpoint = m(eps.SendEmailBookPublishedEndpoint)
	}
	return eps
}
